album/urls.py
from django.contrib import admin
from django.urls import path, include
# 图片保存位置配置
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include(('photo.urls', 'photo'), namespace='photo')),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
# -*- coding: utf-8 -*-
# @Time    : 2021/11/13 15:31
# @Author  : HWN
# @File    : urls.py
# @Software: PyCharm
from django.urls import path

from photo.views import HomeView, UploadView

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('upload/', UploadView.as_view(), name='upload'),
]

photo/models.py
from django.db import models


# Create your models here.

class Photo(models.Model):
    image = models.ImageField(upload_to='photo/%Y%m%d')
    created = models.DateField(auto_now=True)

    class Meta:
        ordering = ('-created',)
        verbose_name_plural = '照片管理'
        db_table = 'tb_image'

    def __str__(self):
        return self.image.name

photo/views.py
from django.contrib.auth import authenticate, login, logout
from django.core.paginator import Paginator
from django.shortcuts import render, redirect

# Create your views here.
from django.urls import reverse
from django.views import View

from photo.models import Photo


class HomeView(View):
    def get(self, request):
        photos = Photo.objects.all()
        paginator = Paginator(photos,5)
        page_num = request.GET.get('page')
        photos = paginator.get_page(page_num)

        return render(request, 'index.html', locals())

    def post(self, request):
        photos = Photo.objects.all()
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        # 登入
        if user is not None and user.is_superuser:
            login(request, user)
        # 登出
        isLogout = request.POST.get('isLogout')
        if isLogout == 'True':
            logout(request)
        return render(request, 'index.html', locals())


# def HomeView(request):
#     photos = Photo.objects.all()
#     if request.method == 'POST':
#         username = request.POST.get('username')
#         password = request.POST.get('password')
#         user = authenticate(request, username=username, password=password)
#         # 登入
#         if user is not None and user.is_superuser:
#             login(request, user)
#         # 登出
#         isLogout = request.POST.get('isLogout')
#         if isLogout == 'True':
#             logout(request)
#     return render(request, 'index.html', locals())


class UploadView(View):
    def get(self, request):
        pass

    def post(self, request):
        if request.user.is_superuser:
            images = request.FILES.getlist('images')
            for image in images:
                Photo.objects.create(image=image)
        return redirect(reverse('photo:index'))

templates/base.html
<!-- /templates/base.html -->

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <!-- 预留页面标题位置 -->
    <title>{% block title %}{% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'hover.css' %}">
    <!-- bootstrap.css -->
    <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC"
            crossorigin="anonymous">
</head>
<body>
<!-- 引入导航栏 -->
{% include 'header.html' %}
<!-- 预留具体页面的位置 -->
{% block content %}{% endblock content %}
<!-- 引入注脚 -->
{% include 'footer.html' %}
<!-- bootstrap.js -->
<script
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
<script
        src="https://cdn.jsdelivr.net/npm/masonry-layout@4.2.2/dist/masonry.pkgd.min.js"
        integrity="sha384-GNFwBvfVxBkLMJpYMOABq3c+d3KnQxudP/mGPkzpZSTYykLBNsZEnG2D9G/X/+7D"
        crossorigin="anonymous"
        async></script>
<!-- 预留脚本的位置 -->
{% block scripts %}{% endblock scripts %}

<style>
    body {
        background-color: #212529;
    }
</style>
</body>
</html>

templates/footer.html
<div><br><br><br></div>
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">
            Copyright &copy; houweinuo 2021
        </p>
    </div>
</footer>

templates/header.html
<!-- /templates/header.html -->

<!-- 导航栏 -->
<nav class="navbar navbar-expand navbar-dark bg-dark">
    <div class="container">
        <!-- 标志 -->
        <a
                class="navbar-brand"
                href="#"
                data-bs-toggle="modal"
                data-bs-target="#login"
        >
            <h2>
                Awesome Album
            </h2>
        </a>
        <!-- 登录模态窗 -->
        {% if user.is_superuser %}
            <ul class="navbar-nav">
                <li class="nav-item">
                    <h2>
                        <a
                                class="nav-link active"
                                href="#"
                                data-bs-toggle="modal"
                                data-bs-target="#upload"
                        >
                            +
                        </a>
                    </h2>
                </li>
            </ul>
        {% endif %}
    </div>
</nav>

<!-- 登出 -->
{% if user.is_superuser %}

    <div class="modal fade" id="login">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <p>确认退出账号吗？</p>
                    <form action="{% url 'photo:index' %}" method="post">
                        {% csrf_token %}
                        <input type="text" id="isLogout" name="isLogout" value="True" hidden>
                        <button type="submit" class="btn btn-danger">Logout</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- 新增上传模态窗 -->
    <div class="modal fade" id="upload">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <h5 class="modal-title">上传图片</h5>
                    <form action="{% url 'photo:upload' %}"
                          method="post"
                          enctype="multipart/form-data"
                    >
                        {% csrf_token %}
                        <div class="col py-2">
                            <input
                                    class="form-control"
                                    type="file"
                                    id="images"
                                    name="images"
                                    multiple="multiple"
                                    accept="image/*"
                            >
                        </div>
                        <button type="submit" class="btn btn-primary">提交</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <!-- 登录 -->
{% else %}

    <div class="modal fade" id="login">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <form action="{% url 'photo:index' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="username" class="form-label">用户名</label>
                            <input type="text" class="form-control" id="username" name="username">
                        </div>
                        <div class="mb-3">
                            <label for="pwd" class="form-label">密码</label>
                            <input type="password" class="form-control" id="pwd" name="password">
                            <div id="passwordHelp" class="form-text">
                                We'll never share your password with anyone else.
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endif %}

templates/index.html
{% extends 'base.html' %}
{% block title %}
    首页
{% endblock %}
{% block content %}
    <div class="container py-2">
        <div class="row" data-masonry='{"percentPosition": true}'>
            {% for photo in photos %}
                <div class="col-4 py-2">
                    <div class="card hvr-float-shadow">
                        <a
                                href="#"
                                data-bs-toggle="modal"
                                data-bs-target="#photo-{{ photo.id }}"
                        >
                            <img
                                    src="{{ photo.image.url }}"
                                    alt=""
                                    class="card-img"
                            >
                        </a>
                    </div>
                </div>
            {% endfor %}
        </div>
{#        分页展示#}
        <div class="row justify-content-center py-5">
            <span class="step-links paginator">
                {% if photos.has_previous %}
                    <a
                            href="?page=1"
                            class="paginator prevnext">
                        &laquo;
                    </a>
                    <a
                            href="?page={{ photos.previous_page_number }}"
                            class="paginator prevnext">
                        {{ photos.previous_page_number }}
                    </a>
                {% endif %}

                <span class="current">
                        {{ photos.number }}
                    </span>

                {% if photos.has_next %}
                    <a
                            href="?page={{ photos.next_page_number }}"
                            class="paginator prevnext">
                        {{ photos.next_page_number }}
                    </a>
                    <a
                            href="?page={{ photos.paginator.num_pages }}"
                            class="paginator prevnext">
                        &raquo;
                    </a>
                {% endif %}
            </span>
        </div>
    </div>

    <!-- 新增了这里 -->
    <!-- 注意下面这部分代码不能直接写在卡片的 for 循环中 -->
    {% for photo in photos %}
        <!-- Modal -->
        <div class="modal fade" id="photo-{{ photo.id }}">
            <div class="modal-dialog modal-dialog-centered modal-lg">
                <div class="modal-content">
                    <div class="modal-body">
                        <img
                                src="{{ photo.image.url }}"
                                alt=""
                                class="card-img"
                        >
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}
    <!-- ************ -->

{% endblock content %}
{% block scripts %}

    <style>
        .paginator {
            color: white;
            text-align: center;
            text-decoration: none;
        }

        .prevnext {
            font-size: x-large;
        }

        .current {
            font-size: xx-large;
            padding-left: 10px;
            padding-right: 10px;
        }
    </style>
{% endblock scripts %}